package main

// import (
	// "encoding/json"
	// "fmt"
	// "log"
	// "os"
	// "strings"
// )

// func main() {
// 	canal1 := make(chan string, 1)
// 	go func() {
// 		time.Sleep(2 * time.Second)
// 		canal1 <- "rezultatul 1"
// 	}()
// 	select {
// 	case result := <-canal1:
// 		fmt.Println(result)
// 	case heyy := <-time.After(1 * time.Second):
// 		fmt.Println("timeout 1")
// 		fmt.Println(heyy)
// 	}
// 	canal2 := make(chan string, 1)
// 	go func() {
// 		time.Sleep(2 * time.Second)
// 		canal2 <- "rezultatul 2"
// 	}()
// 	select {
// 	case res := <-canal2:
// 		fmt.Println(res)
// 	case t2 := <-time.After(3 * time.Second):
// 		fmt.Println("timeout 2")
// 		fmt.Println(t2)
// 	}
// }

// ########################################################

// func main() {
//     if file_content, err := os.ReadFile("./dummy_file.txt"); err == nil {
//         message := string(file_content)
//         content := strings.Split(message, "\n")
//         fmt.Println(content[2])
//         file, err := os.Create("temp.txt")

//         if err != nil {
//             log.Fatal(err)
//             os.Exit(0)
//         }

//         for i := range len(content) {
//             file.WriteString("Line: " + strconv.Itoa(i))
//             file.WriteString("\n")
//             file.WriteString(content[i])
//             file.WriteString("\n")
//             file.WriteString("==================")
//             file.WriteString("\n")
//         }
//         os.Rename("./temp.txt", "./new_temp.md")
//     } else {
//         log.Fatal(err)
//         os.Exit(0)
//     }
// }

// func main() {
//     if file_content, err := os.ReadFile("./temp.json"); err == nil {
//         json_content := string(file_content)

// 		json_encoding, err := json.Marshal(json_content)

// 		var json_decoding string
// 		err = json.Unmarshal(json_encoding, &json_decoding)

// 		file, err := os.Create("result.json")

// 		file.Write(json_encoding)

//         if err != nil {
//             log.Fatal(err)
//             os.Exit(0)
//         }

// 		fmt.Println(json_decoding)
//     } else {
//         log.Fatal(err)
//         os.Exit(0)
//     }
// }

// type CoffeeType struct {
// 	name string
// 	origins []string
// 	description string
// }

// type AutoGenerated struct {
// 	Coffees []struct {
// 		Name        string   `json:"name"`
// 		Origins     []string `json:"origins"`
// 		Description string   `json:"description"`
// 	} `json:"coffees"`
// }

// func (c CoffeeType) String() {
// 	fmt.Sprintf("Name: %s\nOrigins: %s\nDescription: %s",
// 		c.name, strings.Join(c.origins, ", "), c.description)
// }

// func main() {
	// var coffee_types []CoffeeType;
	// if coffee_file, err := os.ReadFile("./coffee_types.json"); err != nil {
	// 	json.
	// }
// }